/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"

void request__init
        (Request *message) {
    static Request init_value = REQUEST__INIT;
    *message = init_value;
}

size_t request__get_packed_size
        (const Request *message) {
    assert(message->base.descriptor == &request__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t request__pack
        (const Request *message,
         uint8_t *out) {
    assert(message->base.descriptor == &request__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t request__pack_to_buffer
        (const Request *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &request__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Request *
request__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (Request *)
            protobuf_c_message_unpack(&request__descriptor,
                                      allocator, len, data);
}

void request__free_unpacked
        (Request *message,
         ProtobufCAllocator *allocator) {
    assert(message->base.descriptor == &request__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void response__init
        (Response *message) {
    static Response init_value = RESPONSE__INIT;
    *message = init_value;
}

size_t response__get_packed_size
        (const Response *message) {
    assert(message->base.descriptor == &response__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t response__pack
        (const Response *message,
         uint8_t *out) {
    assert(message->base.descriptor == &response__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t response__pack_to_buffer
        (const Response *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &response__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Response *
response__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (Response *)
            protobuf_c_message_unpack(&response__descriptor,
                                      allocator, len, data);
}

void response__free_unpacked
        (Response *message,
         ProtobufCAllocator *allocator) {
    assert(message->base.descriptor == &response__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor request__field_descriptors[3] =
        {
                {
                        "username",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Request, username),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "password",
                        2,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Request, password),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "value",
                        3,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_FLOAT,
                        0,   /* quantifier_offset */
                        offsetof(Request, value),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned request__field_indices_by_name[] = {
        1,   /* field[1] = password */
        0,   /* field[0] = username */
        2,   /* field[2] = value */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 3}
        };
const ProtobufCMessageDescriptor request__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "Request",
                "Request",
                "Request",
                "",
                sizeof(Request),
                3,
                request__field_descriptors,
                request__field_indices_by_name,
                1, request__number_ranges,
                (ProtobufCMessageInit) request__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
        {
                {
                        "integer",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(Response, integer),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "decimal",
                        2,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(Response, decimal),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned response__field_indices_by_name[] = {
        1,   /* field[1] = decimal */
        0,   /* field[0] = integer */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 2}
        };
const ProtobufCMessageDescriptor response__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "Response",
                "Response",
                "Response",
                "",
                sizeof(Response),
                2,
                response__field_descriptors,
                response__field_indices_by_name,
                1, response__number_ranges,
                (ProtobufCMessageInit) response__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
