/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"

void request__init
        (Request *message) {
    static Request init_value = REQUEST__INIT;
    *message = init_value;
}

size_t request__get_packed_size
        (const Request *message) {
    assert(message->base.descriptor == &request__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t request__pack
        (const Request *message,
         uint8_t *out) {
    assert(message->base.descriptor == &request__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t request__pack_to_buffer
        (const Request *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &request__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Request *
request__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (Request *)
            protobuf_c_message_unpack(&request__descriptor,
                                      allocator, len, data);
}

void request__free_unpacked
        (Request *message,
         ProtobufCAllocator *allocator) {
    assert(message->base.descriptor == &request__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor request__field_descriptors[2] =
        {
                {
                        "nomeRegione",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Request, nomeregione),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "numero_impianti",
                        2,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(Request, numero_impianti),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned request__field_indices_by_name[] = {
        0,   /* field[0] = nomeRegione */
        1,   /* field[1] = numero_impianti */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 2}
        };
const ProtobufCMessageDescriptor request__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "Request",
                "Request",
                "Request",
                "",
                sizeof(Request),
                2,
                request__field_descriptors,
                request__field_indices_by_name,
                1, request__number_ranges,
                (ProtobufCMessageInit) request__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
