/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Request Request;


/* --- enums --- */


/* --- messages --- */

struct _Request {
    ProtobufCMessage base;
    char *nomeregione;
    int32_t numero_impianti;
};
#define REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__descriptor) \
    , NULL, 0 }


/* Request methods */
void request__init
        (Request *message);

size_t request__get_packed_size
        (const Request *message);

size_t request__pack
        (const Request *message,
         uint8_t *out);

size_t request__pack_to_buffer
        (const Request *message,
         ProtobufCBuffer *buffer);

Request *
request__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data);

void request__free_unpacked
        (Request *message,
         ProtobufCAllocator *allocator);

/* --- per-message closures --- */

typedef void (*Request_Closure)
        (const Request *message,
         void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
