/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"

void com1__init
        (Com1 *message) {
    static Com1 init_value = COM1__INIT;
    *message = init_value;
}

size_t com1__get_packed_size
        (const Com1 *message) {
    assert(message->base.descriptor == &com1__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t com1__pack
        (const Com1 *message,
         uint8_t *out) {
    assert(message->base.descriptor == &com1__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t com1__pack_to_buffer
        (const Com1 *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &com1__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Com1 *
com1__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (Com1 *)
            protobuf_c_message_unpack(&com1__descriptor,
                                      allocator, len, data);
}

void com1__free_unpacked
        (Com1 *message,
         ProtobufCAllocator *allocator) {
    assert(message->base.descriptor == &com1__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void com4__init
        (Com4 *message) {
    static Com4 init_value = COM4__INIT;
    *message = init_value;
}

size_t com4__get_packed_size
        (const Com4 *message) {
    assert(message->base.descriptor == &com4__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t com4__pack
        (const Com4 *message,
         uint8_t *out) {
    assert(message->base.descriptor == &com4__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t com4__pack_to_buffer
        (const Com4 *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &com4__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Com4 *
com4__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (Com4 *)
            protobuf_c_message_unpack(&com4__descriptor,
                                      allocator, len, data);
}

void com4__free_unpacked
        (Com4 *message,
         ProtobufCAllocator *allocator) {
    assert(message->base.descriptor == &com4__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor com1__field_descriptors[3] =
        {
                {
                        "nomefile",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Com1, nomefile),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "testoaggiuntivo",
                        2,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Com1, testoaggiuntivo),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "command",
                        3,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(Com1, command),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned com1__field_indices_by_name[] = {
        2,   /* field[2] = command */
        0,   /* field[0] = nomefile */
        1,   /* field[1] = testoaggiuntivo */
};
static const ProtobufCIntRange com1__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 3}
        };
const ProtobufCMessageDescriptor com1__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "Com1",
                "Com1",
                "Com1",
                "",
                sizeof(Com1),
                3,
                com1__field_descriptors,
                com1__field_indices_by_name,
                1, com1__number_ranges,
                (ProtobufCMessageInit) com1__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
static const ProtobufCFieldDescriptor com4__field_descriptors[4] =
        {
                {
                        "nomefile",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Com4, nomefile),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "testoaggiuntivo",
                        2,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Com4, testoaggiuntivo),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "command",
                        3,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(Com4, command),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "directory",
                        4,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Com4, directory),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned com4__field_indices_by_name[] = {
        2,   /* field[2] = command */
        3,   /* field[3] = directory */
        0,   /* field[0] = nomefile */
        1,   /* field[1] = testoaggiuntivo */
};
static const ProtobufCIntRange com4__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 4}
        };
const ProtobufCMessageDescriptor com4__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "Com4",
                "Com4",
                "Com4",
                "",
                sizeof(Com4),
                4,
                com4__field_descriptors,
                com4__field_indices_by_name,
                1, com4__number_ranges,
                (ProtobufCMessageInit) com4__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
