/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"

void response__init
        (Response *message) {
    static Response init_value = RESPONSE__INIT;
    *message = init_value;
}

size_t response__get_packed_size
        (const Response *message) {
    assert(message->base.descriptor == &response__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t response__pack
        (const Response *message,
         uint8_t *out) {
    assert(message->base.descriptor == &response__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t response__pack_to_buffer
        (const Response *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &response__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Response *
response__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (Response *)
            protobuf_c_message_unpack(&response__descriptor,
                                      allocator, len, data);
}

void response__free_unpacked
        (Response *message,
         ProtobufCAllocator *allocator) {
    assert(message->base.descriptor == &response__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor response__field_descriptors[2] =
        {
                {
                        "stato",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(Response, stato),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "risultato_parziale",
                        2,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_FLOAT,
                        0,   /* quantifier_offset */
                        offsetof(Response, risultato_parziale),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned response__field_indices_by_name[] = {
        1,   /* field[1] = risultato_parziale */
        0,   /* field[0] = stato */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 2}
        };
const ProtobufCMessageDescriptor response__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "Response",
                "Response",
                "Response",
                "",
                sizeof(Response),
                2,
                response__field_descriptors,
                response__field_indices_by_name,
                1, response__number_ranges,
                (ProtobufCMessageInit) response__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
